## Tugas Penambangan Data

In [14]:
from scipy import stats
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
df = pd.read_csv('DataMining_tg1.csv')
df

    Berat Badan  Tinggi Badan  Tekanan Darah  Lingkar Perut
0            66           151            119             56
1            67           178            125             42
2            53           172            129             49
3            62           152             89             63
4            63           175             97             59
5            90           180            121             54
6            74           172            110             48
7            40           163            104             60
8            36           158            108             57
9            43           173            127             41
10           75           154            105             48
11           40           176             95             69
12           86           154            107             40
13           51           166            102             52
14           44           155            127             51
15           66           171             96             51
16           41           179             92             55
17           66           164             97             61
18           83           173            118             41
19           42           177            129             67
20           52           164            115             42
21           64           172            101             57
22           50           177             95             47
23           83           168            116             70
24           47           152             89             51
25           48           169             96             47
26           35           175             99             56
27           79           167            120             44
28           49           168            121             52
29           47           165            104             52
..          ...           ...            ...            ...
70           72           159             97             69
71           38           150            110             68
72           86           177            125             64
73           63           177            127             50
74           60           172             92             62
75           73           162             94             67
76           65           168             87             44
77           64           162            125             67
78           90           180            118             48
79           51           176             96             57
80           52           152             85             60
81           52           154            113             51
82           60           157            107             70
83           73           175             92             65
84           48           176            124             52
85           57           165            107             67
86           78           152             88             46
87           74           157            108             47
88           36           164            117             59
89           43           167            100             41
90           58           163            112             65
91           81           168             98             42
92           46           163            111             48
93           82           177            113             42
94           85           155            108             42
95           59           154            126             41
96           52           166            107             63
97           37           154            129             60
98           73           165             84             55
99           87           162            116             58

[100 rows x 4 columns]

In [13]:
from IPython.display import HTML, display
import tabulate
table=[
        ["method"]+[x for x in df.columns],
        ["count"]+[df[col].count() for col in df.columns],
        ["mean"]+[df[col].mean() for col in df.columns],
        ["std"]+["{:.2f}".format(df[col].std()) for col in df.columns],
        ["min"]+[df[col].min() for col in df.columns],
        ["max"]+[df[col].max() for col in df.columns],
        ["q1"]+[df[col].quantile(0.25) for col in df.columns],
        ["q2"]+[df[col].quantile(0.50) for col in df.columns],
        ["q3"]+[df[col].quantile(0.75) for col in df.columns],
        ["skew"]+["{:.2f}".format(df[col].skew()) for col in df.columns],
     ]

display(HTML(tabulate.tabulate(table, tablefmt='html')))